server:
  servlet:
    context-path: /soulfood
spring:
  application:
    name: soulfood-backend
  datasource:
    url: jdbc:postgresql://pgm-2vc574u66oe06366.pgsql.cn-chengdu.rds.aliyuncs.com:5432/food?stringtype=unspecified
    username: commerce
    password: nxVRjxu6iVKIoTmC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: foodServiceHikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  ai:
    openai:
      api-key: 6044cf7f25964e519efa410456ff7ac0.qbu0U2g6X9CFtXXH
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4-flash
          temperature: 0.7

