SET search_path TO food;

CREATE TABLE sf_user_notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    type         VARCHAR(32)  NOT NULL,
    title        VARCHAR(120) NOT NULL,
    body         VARCHAR(512),
    payload_json TEXT,
    read_flag    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_sf_user_notification_user FOREIGN KEY (user_id) REFERENCES sf_user (id)
);

CREATE INDEX idx_sf_user_notification_user_created ON sf_user_notification (user_id, created_at DESC);
CREATE INDEX idx_sf_user_notification_user_unread ON sf_user_notification (user_id, read_flag);

COMMENT ON TABLE sf_user_notification IS '用户应用内通知';
