-- 好友私聊会话与消息
CREATE TABLE sf_friend_conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_low_id     BIGINT       NOT NULL,
    user_high_id    BIGINT       NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_fc_low FOREIGN KEY (user_low_id) REFERENCES sf_user (id),
    CONSTRAINT fk_sf_fc_high FOREIGN KEY (user_high_id) REFERENCES sf_user (id),
    CONSTRAINT uk_sf_friend_conv_pair UNIQUE (user_low_id, user_high_id),
    CONSTRAINT ck_sf_fc_order CHECK (user_low_id < user_high_id)
);

COMMENT ON TABLE sf_friend_conversation IS '好友一对一聊天会话（user_low_id < user_high_id）';

CREATE INDEX idx_sf_fc_updated_at ON sf_friend_conversation (updated_at DESC);

CREATE TABLE sf_friend_message (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT       NOT NULL,
    sender_id        BIGINT       NOT NULL,
    content          TEXT         NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_fm_conv FOREIGN KEY (conversation_id) REFERENCES sf_friend_conversation (id),
    CONSTRAINT fk_sf_fm_sender FOREIGN KEY (sender_id) REFERENCES sf_user (id),
    CONSTRAINT ck_sf_fm_content CHECK (char_length(trim(content)) > 0)
);

COMMENT ON TABLE sf_friend_message IS '好友聊天消息';

CREATE INDEX idx_sf_fm_conv_id ON sf_friend_message (conversation_id, id DESC);

CREATE TABLE sf_friend_conversation_read (
    conversation_id       BIGINT       NOT NULL,
    user_id               BIGINT       NOT NULL,
    last_read_message_id  BIGINT,
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (conversation_id, user_id),
    CONSTRAINT fk_sf_fcr_conv FOREIGN KEY (conversation_id) REFERENCES sf_friend_conversation (id),
    CONSTRAINT fk_sf_fcr_user FOREIGN KEY (user_id) REFERENCES sf_user (id)
);

COMMENT ON TABLE sf_friend_conversation_read IS '好友会话已读游标';
