-- DecideMeal / SoulFood 初始库表（PostgreSQL）
-- 与 doc/product/decidemeal-前后端开发计划.md §5.6 对齐
-- schema: food（库名 food；RDS 账号对 public 无 CREATE 权限）

CREATE SCHEMA IF NOT EXISTS food;
SET search_path TO food;

-- ---------------------------------------------------------------------------
-- 用户
-- ---------------------------------------------------------------------------
CREATE TABLE sf_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    open_id         VARCHAR(64)  NOT NULL,
    nickname        VARCHAR(64),
    avatar_url      VARCHAR(512),
    signature       VARCHAR(256),
    phone           VARCHAR(20),
    status          SMALLINT     NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_sf_user_open_id UNIQUE (open_id)
);

COMMENT ON TABLE sf_user IS '应用用户';
COMMENT ON COLUMN sf_user.open_id IS '微信等渠道 openId';
COMMENT ON COLUMN sf_user.status IS '1=正常 0=禁用';

CREATE INDEX idx_sf_user_created_at ON sf_user (created_at);

-- ---------------------------------------------------------------------------
-- 组局房间
-- ---------------------------------------------------------------------------
CREATE TABLE sf_room (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            CHAR(6)      NOT NULL,
    topic           VARCHAR(128) NOT NULL,
    max_people      INT          NOT NULL DEFAULT 4,
    duration_min    INT          NOT NULL DEFAULT 20,
    status          VARCHAR(32)  NOT NULL DEFAULT 'open',
    owner_id        BIGINT       NOT NULL,
    winner_option_id BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at       TIMESTAMPTZ,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_sf_room_code UNIQUE (code),
    CONSTRAINT fk_sf_room_owner FOREIGN KEY (owner_id) REFERENCES sf_user (id)
);

COMMENT ON TABLE sf_room IS '组局投票房间';
COMMENT ON COLUMN sf_room.code IS '6 位房间号';
COMMENT ON COLUMN sf_room.status IS 'open|voting|closed';
COMMENT ON COLUMN sf_room.winner_option_id IS '胜出选项，结算后写入';

CREATE INDEX idx_sf_room_owner_id ON sf_room (owner_id);
CREATE INDEX idx_sf_room_status ON sf_room (status);

-- ---------------------------------------------------------------------------
-- 房间投票选项
-- ---------------------------------------------------------------------------
CREATE TABLE sf_room_option (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         BIGINT       NOT NULL,
    title           VARCHAR(128) NOT NULL,
    vote_count      INT          NOT NULL DEFAULT 0,
    source          VARCHAR(16)  NOT NULL DEFAULT 'manual',
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_sf_room_option_room FOREIGN KEY (room_id) REFERENCES sf_room (id),
    CONSTRAINT ck_sf_room_option_source CHECK (source IN ('manual', 'ai'))
);

COMMENT ON TABLE sf_room_option IS '房间投票候选项';
COMMENT ON COLUMN sf_room_option.source IS 'manual=人工 ai=Agent 生成';

CREATE INDEX idx_sf_room_option_room_id ON sf_room_option (room_id);

-- 房间胜出选项外键（选项表创建后再补）
ALTER TABLE sf_room
    ADD CONSTRAINT fk_sf_room_winner_option
    FOREIGN KEY (winner_option_id) REFERENCES sf_room_option (id);

-- ---------------------------------------------------------------------------
-- 投票记录
-- ---------------------------------------------------------------------------
CREATE TABLE sf_vote (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         BIGINT       NOT NULL,
    option_id       BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_vote_room FOREIGN KEY (room_id) REFERENCES sf_room (id),
    CONSTRAINT fk_sf_vote_option FOREIGN KEY (option_id) REFERENCES sf_room_option (id),
    CONSTRAINT fk_sf_vote_user FOREIGN KEY (user_id) REFERENCES sf_user (id),
    CONSTRAINT uk_sf_vote_room_user UNIQUE (room_id, user_id)
);

COMMENT ON TABLE sf_vote IS '用户对房间内某一选项的投票';

CREATE INDEX idx_sf_vote_option_id ON sf_vote (option_id);
CREATE INDEX idx_sf_vote_user_id ON sf_vote (user_id);

-- ---------------------------------------------------------------------------
-- 餐厅 / POI
-- ---------------------------------------------------------------------------
CREATE TABLE sf_restaurant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    category        VARCHAR(32)  NOT NULL,
    address         VARCHAR(256),
    lat             DECIMAL(10, 7),
    lng             DECIMAL(10, 7),
    rating          DECIMAL(3, 1),
    distance_km     DECIMAL(6, 2),
    external_id     VARCHAR(64),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE sf_restaurant IS '附近餐厅/POI 候选';
COMMENT ON COLUMN sf_restaurant.external_id IS '第三方地图 POI ID';

CREATE INDEX idx_sf_restaurant_category ON sf_restaurant (category);
CREATE INDEX idx_sf_restaurant_location ON sf_restaurant (lat, lng);

-- ---------------------------------------------------------------------------
-- 用户口味偏好
-- ---------------------------------------------------------------------------
CREATE TABLE sf_user_preference (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    tags_json       JSONB        NOT NULL DEFAULT '[]'::jsonb,
    spicy_level     SMALLINT     NOT NULL DEFAULT 3,
    sweet_level     SMALLINT     NOT NULL DEFAULT 2,
    no_coriander    BOOLEAN      NOT NULL DEFAULT FALSE,
    no_peanut       BOOLEAN      NOT NULL DEFAULT FALSE,
    allergens_json  JSONB        NOT NULL DEFAULT '[]'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_user_preference_user FOREIGN KEY (user_id) REFERENCES sf_user (id),
    CONSTRAINT uk_sf_user_preference_user_id UNIQUE (user_id),
    CONSTRAINT ck_sf_user_preference_spicy CHECK (spicy_level BETWEEN 1 AND 5),
    CONSTRAINT ck_sf_user_preference_sweet CHECK (sweet_level BETWEEN 1 AND 5)
);

COMMENT ON TABLE sf_user_preference IS '用户口味偏好（对应 13-taste-preference）';
COMMENT ON COLUMN sf_user_preference.tags_json IS '偏好标签数组，如 ["清淡","微辣"]';

-- ---------------------------------------------------------------------------
-- 收藏
-- ---------------------------------------------------------------------------
CREATE TABLE sf_favorite (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    target_type     VARCHAR(16)  NOT NULL,
    target_id       BIGINT,
    title           VARCHAR(128) NOT NULL,
    subtitle        VARCHAR(256),
    meta_json       JSONB,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_sf_favorite_user FOREIGN KEY (user_id) REFERENCES sf_user (id),
    CONSTRAINT ck_sf_favorite_target_type CHECK (target_type IN ('recipe', 'restaurant'))
);

COMMENT ON TABLE sf_favorite IS '收藏（菜谱/餐厅）';

CREATE INDEX idx_sf_favorite_user_id ON sf_favorite (user_id);
CREATE INDEX idx_sf_favorite_user_type ON sf_favorite (user_id, target_type);

-- ---------------------------------------------------------------------------
-- 行为记录（投票/吃过等时间线）
-- ---------------------------------------------------------------------------
CREATE TABLE sf_activity_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    record_type     VARCHAR(32)  NOT NULL,
    title           VARCHAR(128) NOT NULL,
    summary         VARCHAR(512),
    ref_id          BIGINT,
    extra_json      JSONB,
    occurred_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_activity_record_user FOREIGN KEY (user_id) REFERENCES sf_user (id),
    CONSTRAINT ck_sf_activity_record_type CHECK (record_type IN ('vote', 'favorite', 'eat', 'ai_recommend'))
);

COMMENT ON TABLE sf_activity_record IS '我的记录时间线（08-record）';

CREATE INDEX idx_sf_activity_record_user_time ON sf_activity_record (user_id, occurred_at DESC);

-- ---------------------------------------------------------------------------
-- 历史订单
-- ---------------------------------------------------------------------------
CREATE TABLE sf_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    restaurant_name VARCHAR(128) NOT NULL,
    category        VARCHAR(32),
    amount          DECIMAL(10, 2),
    item_summary    VARCHAR(256),
    ordered_at      TIMESTAMPTZ  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_sf_order_user FOREIGN KEY (user_id) REFERENCES sf_user (id)
);

COMMENT ON TABLE sf_order IS '历史订单（14-order-history）';

CREATE INDEX idx_sf_order_user_ordered ON sf_order (user_id, ordered_at DESC);

-- ---------------------------------------------------------------------------
-- 邀请
-- ---------------------------------------------------------------------------
CREATE TABLE sf_invite (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inviter_id      BIGINT       NOT NULL,
    invite_code     VARCHAR(16)  NOT NULL,
    invitee_id      BIGINT,
    status          VARCHAR(16)  NOT NULL DEFAULT 'pending',
    reward_status   VARCHAR(16)  NOT NULL DEFAULT 'none',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TIMESTAMPTZ,
    CONSTRAINT fk_sf_invite_inviter FOREIGN KEY (inviter_id) REFERENCES sf_user (id),
    CONSTRAINT fk_sf_invite_invitee FOREIGN KEY (invitee_id) REFERENCES sf_user (id),
    CONSTRAINT ck_sf_invite_status CHECK (status IN ('pending', 'completed', 'expired'))
);

COMMENT ON TABLE sf_invite IS '邀请记录（15-invite-friends）';

CREATE INDEX idx_sf_invite_inviter ON sf_invite (inviter_id);
CREATE UNIQUE INDEX uk_sf_invite_code ON sf_invite (invite_code);

-- ---------------------------------------------------------------------------
-- 用户「想去」餐厅标记
-- ---------------------------------------------------------------------------
CREATE TABLE sf_restaurant_want (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    restaurant_id   BIGINT       NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_restaurant_want_user FOREIGN KEY (user_id) REFERENCES sf_user (id),
    CONSTRAINT fk_sf_restaurant_want_restaurant FOREIGN KEY (restaurant_id) REFERENCES sf_restaurant (id),
    CONSTRAINT uk_sf_restaurant_want UNIQUE (user_id, restaurant_id)
);

COMMENT ON TABLE sf_restaurant_want IS '附近觅食「想去」标记（05-cook-mode）';
