-- 好友关系（邀请注册 / 主动添加）
CREATE TABLE sf_friend (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    friend_user_id  BIGINT       NOT NULL,
    source          VARCHAR(16)  NOT NULL DEFAULT 'invite',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_friend_user FOREIGN KEY (user_id) REFERENCES sf_user (id),
    CONSTRAINT fk_sf_friend_friend FOREIGN KEY (friend_user_id) REFERENCES sf_user (id),
    CONSTRAINT uk_sf_friend_pair UNIQUE (user_id, friend_user_id),
    CONSTRAINT ck_sf_friend_source CHECK (source IN ('invite', 'manual')),
    CONSTRAINT ck_sf_friend_not_self CHECK (user_id <> friend_user_id)
);

COMMENT ON TABLE sf_friend IS '用户好友关系（双向各存一行）';
COMMENT ON COLUMN sf_friend.source IS 'invite=邀请注册 manual=主动添加';

CREATE INDEX idx_sf_friend_user_id ON sf_friend (user_id);

-- 同一邀请码可被多人使用，去掉错误的全局唯一约束
DROP INDEX IF EXISTS uk_sf_invite_code;
CREATE UNIQUE INDEX uk_sf_invite_inviter_invitee
    ON sf_invite (inviter_id, invitee_id)
    WHERE invitee_id IS NOT NULL;

-- 历史邀请记录回填好友
INSERT INTO sf_friend (user_id, friend_user_id, source, created_at)
SELECT i.inviter_id, i.invitee_id, 'invite', COALESCE(i.completed_at, i.created_at)
FROM sf_invite i
WHERE i.invitee_id IS NOT NULL
  AND i.status = 'completed'
  AND NOT EXISTS (
      SELECT 1 FROM sf_friend f
      WHERE f.user_id = i.inviter_id AND f.friend_user_id = i.invitee_id
  );

INSERT INTO sf_friend (user_id, friend_user_id, source, created_at)
SELECT i.invitee_id, i.inviter_id, 'invite', COALESCE(i.completed_at, i.created_at)
FROM sf_invite i
WHERE i.invitee_id IS NOT NULL
  AND i.status = 'completed'
  AND NOT EXISTS (
      SELECT 1 FROM sf_friend f
      WHERE f.user_id = i.invitee_id AND f.friend_user_id = i.inviter_id
  );
