-- AI 对话会话与消息（替代内存 ChatMemory）
CREATE TABLE sf_ai_conversation (
    id          VARCHAR(64)  PRIMARY KEY,
    user_id     BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_ai_conversation_user FOREIGN KEY (user_id) REFERENCES sf_user (id)
);

COMMENT ON TABLE sf_ai_conversation IS 'AI 对话会话';
COMMENT ON COLUMN sf_ai_conversation.id IS 'conversationId（UUID）';

CREATE INDEX idx_sf_ai_conversation_user_id ON sf_ai_conversation (user_id);
CREATE INDEX idx_sf_ai_conversation_updated ON sf_ai_conversation (updated_at DESC);

CREATE TABLE sf_ai_chat_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64)  NOT NULL,
    sort_order      INT          NOT NULL DEFAULT 0,
    message_type    VARCHAR(16)  NOT NULL,
    content         TEXT         NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sf_ai_chat_message_conversation
        FOREIGN KEY (conversation_id) REFERENCES sf_ai_conversation (id) ON DELETE CASCADE,
    CONSTRAINT ck_sf_ai_chat_message_type
        CHECK (message_type IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL'))
);

COMMENT ON TABLE sf_ai_chat_message IS 'AI 对话消息上下文';

CREATE INDEX idx_sf_ai_chat_message_conversation
    ON sf_ai_chat_message (conversation_id, sort_order);
