-- 菜品库
CREATE TABLE sf_recipe (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    category        VARCHAR(32)  NOT NULL,
    difficulty      VARCHAR(16)  NOT NULL DEFAULT '简单',
    duration_min    INT          NOT NULL DEFAULT 30,
    score           DECIMAL(3, 1) NOT NULL DEFAULT 4.5,
    summary         VARCHAR(512),
    ingredients_json JSONB       NOT NULL DEFAULT '[]'::jsonb,
    steps_json      JSONB        NOT NULL DEFAULT '[]'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE sf_recipe IS '菜品/菜谱库';

CREATE INDEX idx_sf_recipe_category ON sf_recipe (category);
CREATE INDEX idx_sf_recipe_name ON sf_recipe (name);

INSERT INTO sf_recipe (name, category, difficulty, duration_min, score, summary, ingredients_json, steps_json)
SELECT '番茄炒蛋', '家常菜', '简单', 15, 4.8,
       '经典下饭菜，酸甜开胃，十分钟搞定。',
       '["鸡蛋 3 个","番茄 2 个","葱花","盐","糖","食用油"]'::jsonb,
       '["番茄切块，鸡蛋打散","热油炒蛋至凝固盛出","炒番茄出汁后倒回鸡蛋","加盐糖调味，撒葱花"]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM sf_recipe WHERE name = '番茄炒蛋');

INSERT INTO sf_recipe (name, category, difficulty, duration_min, score, summary, ingredients_json, steps_json)
SELECT '麻婆豆腐', '川菜', '中等', 25, 4.7,
       '麻辣鲜香，豆腐嫩滑，配米饭一绝。',
       '["北豆腐 1 块","牛肉末","郫县豆瓣","花椒","葱蒜","淀粉"]'::jsonb,
       '["豆腐切块焯水","炒香肉末与豆瓣","加水下豆腐小火煮","勾芡撒花椒粉"]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM sf_recipe WHERE name = '麻婆豆腐');

INSERT INTO sf_recipe (name, category, difficulty, duration_min, score, summary, ingredients_json, steps_json)
SELECT '清炒时蔬', '素菜', '简单', 10, 4.5,
       '低油清爽，保留蔬菜本味。',
       '["时令蔬菜","蒜片","盐","食用油"]'::jsonb,
       '["蔬菜洗净切段","热油爆香蒜片","大火快炒蔬菜","盐调味出锅"]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM sf_recipe WHERE name = '清炒时蔬');

INSERT INTO sf_recipe (name, category, difficulty, duration_min, score, summary, ingredients_json, steps_json)
SELECT '红烧肉', '硬菜', '中等', 60, 4.9,
       '肥而不腻，入口即化，宴客必备。',
       '["五花肉","冰糖","生抽","老抽","料酒","姜","八角"]'::jsonb,
       '["五花肉切块焯水","炒糖色下肉上色","加调料与热水慢炖","大火收汁"]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM sf_recipe WHERE name = '红烧肉');

INSERT INTO sf_recipe (name, category, difficulty, duration_min, score, summary, ingredients_json, steps_json)
SELECT '酸辣土豆丝', '家常菜', '简单', 20, 4.6,
       '爽脆酸辣，家常快手小炒。',
       '["土豆","干辣椒","醋","盐","食用油"]'::jsonb,
       '["土豆切丝泡水","热油爆辣椒","快炒土豆丝","淋醋盐调味"]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM sf_recipe WHERE name = '酸辣土豆丝');

INSERT INTO sf_recipe (name, category, difficulty, duration_min, score, summary, ingredients_json, steps_json)
SELECT '菌菇鸡汤', '汤羹', '简单', 45, 4.8,
       '鲜甜暖胃，适合秋冬。',
       '["半鸡","各类菌菇","姜","枸杞","盐"]'::jsonb,
       '["鸡肉焯水","与菌菇同炖","小火煲 40 分钟","加盐枸杞即可"]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM sf_recipe WHERE name = '菌菇鸡汤');

-- AI 会话标题
ALTER TABLE sf_ai_conversation ADD COLUMN IF NOT EXISTS title VARCHAR(128);

COMMENT ON COLUMN sf_ai_conversation.title IS '会话标题（首条用户消息摘要）';

-- 收藏类型扩展：AI 回复
ALTER TABLE sf_favorite DROP CONSTRAINT IF EXISTS ck_sf_favorite_target_type;
ALTER TABLE sf_favorite ADD CONSTRAINT ck_sf_favorite_target_type
    CHECK (target_type IN ('recipe', 'restaurant', 'ai_reply'));

COMMENT ON TABLE sf_favorite IS '收藏（菜谱/餐厅/AI 回复）';
